services: 
  reactjs-srv: 
    image: voysopheaktra/reactjs-jenkins-nginx:v1.0.0
    build: . 
    pull_policy: build
    container_name: reactjs-jenkins-cont
    ports: 
      - "3000:80"

# docker compose up -d --build