---
- name: Deploy Reactjs Playbook 
  hosts: 
    - worker02
  vars: 
    image_name: "reactjs-jenkins-nginx:v1.0.0"
  tasks: 
    - name: Start Reactjs with docker compose
      docker_compose: 
        project_name: reactjs-new-srv
        definition:
          services:
            reactjs_srv:   
              image: 69966/{{ image_name }}
              container_name: reactjs-new-cont
              ports: 
                - "3000:80"
    - name: Adding domain for the website 
      debug: 
        msg: "Domain name is not yet ready!!"